run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
  disable:
    - err113

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-dirs:
    - vendor/
    - pkg/
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
