name: Server CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
    - name: Run Go tests
      run: go test ./...
      working-directory: server
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: server
